version: '8.9'

services:

  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=biblioteca
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
    ports:
      - '3306:3306'
volumes:
  localstack-tmp:
